senators = {
    "Shelby, Richard C.": 1,
    "Tuberville, Tommy": 1,
    "Murkowski, Lisa A.": 1,
    "Sullivan, Dan": 1,
    "Kelly, Mark": 1,
    "Sinema, Kyrsten": 1,
    "Boozman, John N.": 1,
    "Cotton, Tom": 1,
    "Feinstein, Dianne": 1,
    "Padilla, Alex": 1,
    "Bennet, Michael": 1,
    "Hickenlooper, John": 1,
    "Blumenthal, Richard": 1,
    "Murphy, Chris S.": 1,
    "Carper, Tom": 1,
    "Coons, Chris": 1,
    "Rubio, Marco": 1,
    "Scott, Rick": 1,
    "Ossoff, Jon": 1,
    "Warnock, Raphael": 1,
    "Hirono, Mazie K.": 1,
    "Schatz, Brian Emanuel": 1,
    "Crapo, Michael D.": 1,
    "Risch, Jim": 1,
    "Duckworth, Tammy": 1,
    "Durbin, Dick": 1,
    "Braun, Mike": 1,
    "Young, Todd": 1,
    "Ernst, Joni": 1,
    "Grassley, Chuck E.": 1,
    "Marshall, Roger": 1,
    "Moran, Jerry": 1,
    "McConnell, Mitch": 1,
    "Paul, Rand": 1,
    "Cassidy, Bill": 1,
    "Kennedy, John Neely": 1,
    "Collins, Susan M.": 1,
    "King, Angus": 1,
    "Cardin, Benjamin L.": 1,
    "Van Hollen, Chris": 1,
    "Markey, Ed": 1,
    "Warren, Elizabeth": 1,
    "Peters, Gary C.": 1,
    "Stabenow, Debbie": 1,
    "Klobuchar, Amy": 1,
    "Smith, Tina": 1,
    "Hyde-Smith, Cindy": 1,
    "Wicker, Roger F.": 1,
    "Blunt, Roy": 1,
    "Hawley, Joshua": 1,
    "Daines, Steve": 1,
    "Tester, Jon": 1,
    "Fischer, Deb": 1,
    "Sasse, Benjamin Eric": 1,
    "Cortez Masto, Catherine": 1,
    "Rosen, Jacky": 1,
    "Hassan, Margaret Wood": 1,
    "Shaheen, Jeanne": 1,
    "Booker, Cory Anthony": 1,
    "Menendez, Robert": 1,
    "Heinrich, Martin T.": 1,
    "Luján, Ben Ray": 1,
    "Gillibrand, Kirsten E.": 1,
    "Schumer, Chuck": 1,
    "Burr, Richard M.": 1,
    "Tillis, Thom": 1,
    "Cramer, Kevin": 1,
    "Hoeven, John": 1,
    "Brown, Sherrod C.": 1,
    "Portman, Rob": 1,
    "Inhofe, James M.": 1,
    "Lankford, James": 1,
    "Merkley, Jeff": 1,
    "Wyden, Ron": 1,
    "Casey, Bob": 1,
    "Toomey, Pat": 1,
    "Reed, Jack": 1,
    "Whitehouse, Sheldon": 1,
    "Graham, Lindsey O.": 1,
    "Scott, Tim": 1,
    "Rounds, Mike": 1,
    "Thune, John R.": 1,
    "Blackburn, Marsha": 1,
    "Hagerty, Bill": 1,
    "Cornyn, John": 1,
    "Cruz, Ted": 1,
    "Lee, Mike": 1,
    "Romney, Mitt": 1,
    "Leahy, Patrick J.": 1,
    "Sanders, Bernie": 1,
    "Kaine, Timothy": 1,
    "Warner, Mark R.": 1,
    "Cantwell, Maria": 1,
    "Murray, Patty": 1,
    "Capito, Shelley Moore": 1,
    "Manchin III, Joe": 1,
    "Baldwin, Tammy": 1,
    "Johnson, Ron": 1,
    "Barrasso, John": 1,
    "Lummis, Cynthia M.": 1
}